// Testing attractions controller
// This file was generated by IA based on the file auth.controller.test.ts
// The logic of creating a fake object at the beggining to be reused accross tests 
// is also now inclued in auth as a good idea to avoid code duplication and make tests more readable.

// SETUP
// =====

vi.mock('../../lib/prisma.js', () => ({
    prisma: {
        attraction: {
            findMany: vi.fn(),
            findUnique: vi.fn(),
            create: vi.fn(),
            delete: vi.fn(),
            update: vi.fn()
        },
        user: {
            findUnique: vi.fn()
        }
    }
}))

vi.mock('argon2', () => ({
    verify: vi.fn()
}))

import { describe, it, expect, vi, beforeEach } from 'vitest'
import { getAttractions, getAttractionById, createAttraction, deleteAttraction, updateAttraction } from '../../controllers/attraction.controller.js'
import { prisma } from '../../lib/prisma.js'
import * as argon2 from 'argon2'
import type { Attraction } from '@prisma/client'

// Fake attraction reused across tests
const fakeAttraction = {
    id_ATTRACTION: 1,
    name: 'Zone de Quarantaine',
    description: 'Une attraction terrifiante',
    image: null,
    min_height: 120,
    duration: 30,
    capacity: 20,
    intensity: 'HIGH',
    created_at: new Date(),
    updated_at: new Date()
} satisfies Attraction

// TESTS
// =====

// GET ALL ATTRACTIONS
// ===================

describe('getAttractions', () => {

    beforeEach(() => { vi.clearAllMocks() })

    it('should return 200 with list of attractions', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findMany).mockResolvedValue([fakeAttraction])
        const req = { query: {} } as any
        const res = { json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await getAttractions(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).not.toHaveBeenCalled()
        expect(res.json).toHaveBeenCalledWith([fakeAttraction])
    })
})

// GET ATTRACTION BY ID
// ====================

describe('getAttractionById', () => {

    beforeEach(() => { vi.clearAllMocks() })

    it('should return 400 if id is invalid', async () => {
        // ARRANGE
        const req = { params: { id: 'abc' } } as any
        const res = { json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await getAttractionById(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).toHaveBeenCalledWith(
            expect.objectContaining({ statusCode: 400 })
        )
    })

    it('should return 404 if attraction does not exist', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findUnique).mockResolvedValue(null)
        const req = { params: { id: '999' } } as any
        const res = { json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await getAttractionById(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).toHaveBeenCalledWith(
            expect.objectContaining({ statusCode: 404 })
        )
    })

    it('should return 200 with attraction data', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findUnique).mockResolvedValue(fakeAttraction as any)
        const req = { params: { id: '1' } } as any
        const res = { json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await getAttractionById(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).not.toHaveBeenCalled()
        expect(res.json).toHaveBeenCalledWith(expect.objectContaining({ id_ATTRACTION: 1 }))
    })
})

// CREATE ATTRACTION
// =================

describe('createAttraction', () => {

    beforeEach(() => { vi.clearAllMocks() })

    it('should return 401 if password is incorrect', async () => {
        // ARRANGE
        vi.mocked(prisma.user.findUnique).mockResolvedValue({ id_USER: 1, password: 'hashedPassword' } as any)
        vi.mocked(argon2.verify).mockResolvedValue(false)
        const req = { user: { id: 1 }, body: { name: 'Test', password: 'wrongPassword' } } as any
        const res = { status: vi.fn().mockReturnThis(), json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await createAttraction(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).toHaveBeenCalledWith(
            expect.objectContaining({ statusCode: 401 })
        )
    })

    it('should return 201 on successful creation', async () => {
        // ARRANGE
        vi.mocked(prisma.user.findUnique).mockResolvedValue({ id_USER: 1, password: 'hashedPassword' } as any)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        vi.mocked(prisma.attraction.create).mockResolvedValue(fakeAttraction)
        const req = { user: { id: 1 }, body: { name: 'Zone de Quarantaine', password: 'Password1!' } } as any
        const res = { status: vi.fn().mockReturnThis(), json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await createAttraction(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).not.toHaveBeenCalled()
        expect(res.status).toHaveBeenCalledWith(201)
        expect(res.json).toHaveBeenCalled()
    })
})

// DELETE ATTRACTION
// =================

describe('deleteAttraction', () => {

    beforeEach(() => { vi.clearAllMocks() })

    it('should return 404 if attraction does not exist', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findUnique).mockResolvedValue(null)
        const req = { params: { id: '999' }, user: { id: 1 }, body: {} } as any
        const res = { status: vi.fn().mockReturnThis(), send: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await deleteAttraction(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).toHaveBeenCalledWith(
            expect.objectContaining({ statusCode: 404 })
        )
    })

    it('should return 204 on successful deletion', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findUnique).mockResolvedValue(fakeAttraction)
        vi.mocked(prisma.user.findUnique).mockResolvedValue({ id_USER: 1, password: 'hashedPassword' } as any)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        vi.mocked(prisma.attraction.delete).mockResolvedValue(fakeAttraction)
        const req = { params: { id: '1' }, user: { id: 1 }, body: { password: 'Password1!' } } as any
        const res = { status: vi.fn().mockReturnThis(), send: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await deleteAttraction(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).not.toHaveBeenCalled()
        expect(res.status).toHaveBeenCalledWith(204)
    })
})

// UPDATE ATTRACTION
// =================

describe('updateAttraction', () => {

    beforeEach(() => { vi.clearAllMocks() })

    it('should return 404 if attraction does not exist', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findUnique).mockResolvedValue(null)
        const req = { params: { id: '999' }, user: { id: 1 }, body: {} } as any
        const res = { json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await updateAttraction(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).toHaveBeenCalledWith(
            expect.objectContaining({ statusCode: 404 })
        )
    })

    it('should return 200 on successful update', async () => {
        // ARRANGE
        vi.mocked(prisma.attraction.findUnique).mockResolvedValue(fakeAttraction)
        vi.mocked(prisma.user.findUnique).mockResolvedValue({ id_USER: 1, password: 'hashedPassword' } as any)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        vi.mocked(prisma.attraction.update).mockResolvedValue({ ...fakeAttraction, name: 'Nouveau nom' })
        const req = { params: { id: '1' }, user: { id: 1 }, body: { name: 'Nouveau nom', password: 'Password1!' } } as any
        const res = { json: vi.fn() } as any
        const next = vi.fn()

        // ACT
        try { await updateAttraction(req, res, next) } catch (err) { next(err) }

        // ASSERT
        expect(next).not.toHaveBeenCalled()
        expect(res.json).toHaveBeenCalledWith(
            expect.objectContaining({ name: 'Nouveau nom' })
        )
    })
})