// Testing attraction routes
// This file was generated by IA based on the file auth.routes.test.ts

// SETUP : replacing external dependencies with mocks
// ==================================================

const mockPrisma = vi.hoisted(() => ({
    attraction: {
        findMany: vi.fn(),
        findUnique: vi.fn(),
        create: vi.fn(),
        delete: vi.fn(),
        update: vi.fn()
    },
    user: {
        findUnique: vi.fn()
    }
}))

const mockCheckToken = vi.hoisted(() => vi.fn())
const mockCheckRole = vi.hoisted(() => vi.fn())

vi.mock('@prisma/adapter-pg', () => ({ PrismaPg: class { } }))
vi.mock('@prisma/client', () => ({
    PrismaClient: class { constructor() { Object.assign(this, mockPrisma) } }
}))
vi.mock('../../middlewares/auth.middleware.js', () => ({
    checkToken: mockCheckToken
}))
vi.mock('../../middlewares/role.middleware.js', () => ({
    checkRole: vi.fn(() => (req: any, res: any, next: any) => next())
}))
vi.mock('argon2', () => ({
    verify: vi.fn(),
    hash: vi.fn().mockResolvedValue('hashedPassword')
}))

import { describe, test, expect, vi, beforeEach } from 'vitest'
import { Request, Response, NextFunction } from 'express'
import supertest from 'supertest'
import app from '../../app.js'
import { UnauthorizedError } from '../../utils/AppError.js'
import * as argon2 from 'argon2'
import type { Attraction, User } from '@prisma/client'

const fakeUser = {
    id_USER: 1,
    email: 'admin@example.com',
    password: 'hashedPassword',
    firstname: 'Admin',
    lastname: 'User',
    role: 'ADMIN',
    created_at: new Date(),
    updated_at: new Date()
} satisfies User

const fakeAttraction = {
    id_ATTRACTION: 1,
    name: 'Zone de Quarantaine',
    description: 'Une attraction terrifiante',
    image: null,
    min_height: 120,
    duration: 30,
    capacity: 20,
    intensity: 'HIGH',
    created_at: new Date(),
    updated_at: new Date()
} satisfies Attraction

beforeEach(() => {
    vi.clearAllMocks()
    // Default: admin is authenticated
    mockCheckToken.mockImplementation((
        req: Request & { user?: { id: number; role: string } },
        res: Response,
        next: NextFunction) => {
        req.user = { id: 1, role: 'ADMIN' }
        next()
    })
})
// TESTS
// =====

describe('GET /api/attractions', () => {
    test('devrait retourner 200 avec la liste des attractions', async () => {
        // ARRANGE
        mockPrisma.attraction.findMany.mockResolvedValue([fakeAttraction])

        // ACT
        const response = await supertest(app).get('/api/attractions')

        // ASSERT
        expect(response.status).toEqual(200)
        expect(response.body).toHaveProperty('length')
    })
})

describe('GET /api/attractions/:id', () => {
    test('devrait retourner 400 si l\'id est invalide', async () => {
        // ACT
        const response = await supertest(app).get('/api/attractions/abc')

        // ASSERT
        expect(response.status).toEqual(400)
    })

    test('devrait retourner 404 si l\'attraction n\'existe pas', async () => {
        // ARRANGE
        mockPrisma.attraction.findUnique.mockResolvedValue(null)

        // ACT
        const response = await supertest(app).get('/api/attractions/999')

        // ASSERT
        expect(response.status).toEqual(404)
    })

    test('devrait retourner 200 avec les données de l\'attraction', async () => {
        // ARRANGE
        mockPrisma.attraction.findUnique.mockResolvedValue(fakeAttraction)

        // ACT
        const response = await supertest(app).get('/api/attractions/1')

        // ASSERT
        expect(response.status).toEqual(200)
        expect(response.body).toHaveProperty('id_ATTRACTION')
    })
})

describe('POST /api/attractions', () => {
    test('devrait retourner 401 si le mot de passe est incorrect', async () => {
        // ARRANGE
        mockPrisma.user.findUnique.mockResolvedValue(fakeUser)
        vi.mocked(argon2.verify).mockResolvedValue(false)

        // ACT
        const response = await supertest(app).post('/api/attractions').send({
            name: 'Zone de Quarantaine',
            description: 'Une attraction terrifiante',
            min_height: 120,
            duration: 30,
            capacity: 20,
            intensity: 'HIGH',
            password: 'wrongPassword'
        })

        // ASSERT
        expect(response.status).toEqual(401)
    })

    test('devrait retourner 201 si la création est réussie', async () => {
        // ARRANGE
        mockPrisma.user.findUnique.mockResolvedValue(fakeUser)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        mockPrisma.attraction.create.mockResolvedValue(fakeAttraction)

        // ACT
        const response = await supertest(app).post('/api/attractions').send({
            name: 'Zone de Quarantaine',
            description: 'Une attraction terrifiante',
            min_height: 120,
            duration: 30,
            capacity: 20,
            intensity: 'HIGH',
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(201)
        expect(response.body).toHaveProperty('id_ATTRACTION')
    })
})

describe('DELETE /api/attractions/:id', () => {
    test('devrait retourner 404 si l\'attraction n\'existe pas', async () => {
        // ARRANGE
        mockPrisma.attraction.findUnique.mockResolvedValue(null)

        // ACT
        const response = await supertest(app).delete('/api/attractions/999').send({
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(404)
    })

    test('devrait retourner 204 si la suppression est réussie', async () => {
        // ARRANGE
        mockPrisma.attraction.findUnique.mockResolvedValue(fakeAttraction)
        mockPrisma.user.findUnique.mockResolvedValue(fakeUser)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        mockPrisma.attraction.delete.mockResolvedValue(fakeAttraction)

        // ACT
        const response = await supertest(app).delete('/api/attractions/1').send({
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(204)
    })
})

describe('PATCH /api/attractions/:id', () => {
    test('devrait retourner 404 si l\'attraction n\'existe pas', async () => {
        // ARRANGE
        mockPrisma.attraction.findUnique.mockResolvedValue(null)

        // ACT
        const response = await supertest(app).patch('/api/attractions/999').send({
            name: 'Nouveau nom',
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(404)
    })

    test('devrait retourner 200 si la mise à jour est réussie', async () => {
        // ARRANGE
        mockPrisma.attraction.findUnique.mockResolvedValue(fakeAttraction)
        mockPrisma.user.findUnique.mockResolvedValue(fakeUser)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        mockPrisma.attraction.update.mockResolvedValue({ ...fakeAttraction, name: 'Nouveau nom' })

        // ACT
        const response = await supertest(app).patch('/api/attractions/1').send({
            name: 'Nouveau nom',
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(200)
        expect(response.body).toHaveProperty('name', 'Nouveau nom')
    })
})