// Testing setting routes
// This file was generated by IA based on the file auth.routes.test.ts

// SETUP
// =====

const mockPrisma = vi.hoisted(() => ({
    setting: {
        findUnique: vi.fn(),
        update: vi.fn()
    },
    user: {
        findUnique: vi.fn()
    }
}))

const mockCheckToken = vi.hoisted(() => vi.fn())

vi.mock('@prisma/adapter-pg', () => ({ PrismaPg: class { } }))
vi.mock('@prisma/client', () => ({
    PrismaClient: class { constructor() { Object.assign(this, mockPrisma) } }
}))
vi.mock('../../middlewares/auth.middleware.js', () => ({
    checkToken: mockCheckToken
}))
vi.mock('../../middlewares/role.middleware.js', () => ({
    checkRole: vi.fn(() => (req: any, res: any, next: any) => next())
}))
vi.mock('argon2', () => ({
    verify: vi.fn(),
    hash: vi.fn().mockResolvedValue('hashedPassword')
}))

import { describe, test, expect, vi, beforeEach } from 'vitest'
import { Request, Response, NextFunction } from 'express'
import supertest from 'supertest'
import app from '../../app.js'
import { UnauthorizedError } from '../../utils/AppError.js'
import * as argon2 from 'argon2'

const fakeSetting = { key: 'max_tickets_per_day', value: '9999', updated_at: new Date() }
const fakeAdmin = { id_USER: 1, password: 'hashedPassword' }

beforeEach(() => {
    vi.clearAllMocks()
    mockCheckToken.mockImplementation((
        req: Request & { user?: { id: number; role: string } },
        res: Response,
        next: NextFunction) => {
        req.user = { id: 1, role: 'ADMIN' }
        next()
    })
})

// TESTS
// =====

describe('GET /api/settings', () => {
    test('devrait retourner 404 si le paramètre n\'existe pas', async () => {
        // ARRANGE
        mockPrisma.setting.findUnique.mockResolvedValue(null)

        // ACT
        const response = await supertest(app).get('/api/settings')

        // ASSERT
        expect(response.status).toEqual(404)
    })

    test('devrait retourner 200 avec la valeur du plafond', async () => {
        // ARRANGE
        mockPrisma.setting.findUnique.mockResolvedValue(fakeSetting)

        // ACT
        const response = await supertest(app).get('/api/settings')

        // ASSERT
        expect(response.status).toEqual(200)
        expect(response.body).toHaveProperty('value', 9999)
    })
})

describe('PATCH /api/settings', () => {
    test('devrait retourner 401 si non authentifié', async () => {
        // ARRANGE
        mockCheckToken.mockImplementationOnce((req: any, res: any, next: any) => {
            next(new UnauthorizedError('Token manquant'))
        })

        // ACT
        const response = await supertest(app).patch('/api/settings').send({
            value: 5000,
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(401)
    })

    test('devrait retourner 401 si mot de passe incorrect', async () => {
        // ARRANGE
        mockPrisma.user.findUnique.mockResolvedValue(fakeAdmin)
        vi.mocked(argon2.verify).mockResolvedValue(false)

        // ACT
        const response = await supertest(app).patch('/api/settings').send({
            value: 5000,
            password: 'wrongPassword'
        })

        // ASSERT
        expect(response.status).toEqual(401)
    })

    test('devrait retourner 200 si mise à jour réussie', async () => {
        // ARRANGE
        mockPrisma.user.findUnique.mockResolvedValue(fakeAdmin)
        vi.mocked(argon2.verify).mockResolvedValue(true)
        mockPrisma.setting.update.mockResolvedValue(fakeSetting)

        // ACT
        const response = await supertest(app).patch('/api/settings').send({
            value: 5000,
            password: 'Password1!'
        })

        // ASSERT
        expect(response.status).toEqual(200)
        expect(response.body).toHaveProperty('message')
    })
})